---
icaro:
  url: "https://github.com/nethesis/icaro"
  version: "autobuild"
  hostname: "localhost"
  tls_self_signed: true
  db_root_password: "YourMariaDBPassWordHere"
  sun_api_origin: "http://localhost:8080"
  wax_origin: "http://localhost:8181"
  sun_api:
    db_hostname: "localhost"
    db_username: "sun-api"
    db_password: "Sun-ApiMariaDBPassWordHere"
  wax:
    db_hostname: "localhost"
    db_username: "wax"
    db_password: "WaxMariaDBPassWordHere"
    facebook_client_id: "FacebookClientID"
    facebook_client_secret: "FacebookClientSecret"
    linkedin_client_id: "LinkedInClientID"
    linkedin_client_secret: "LinkedInClientSecret"
    instagram_client_id: "InstagramClientID"
    instagram_client_secret: "InstagramClientSecret"
    twilio_account_sid: "TwilioAccountSID"
    twilio_auth_token: "TwilioAuthToken"
    twilio_number: "TwilioNumber"
    email_from: "admin@example.com"
    email_smtp_host: "EmailSMTPHost"
    email_smtp_port: "25"
    email_smtp_user: "EmailSMTPUser"
    email_smtp_password: "EmailSMTPPassword"
