---

- name: Create Icaro static directory
  file:
    path: /opt/icaro/static
    state: directory
    recurse: yes

- name: Create Sun-api templates directory
  file:
    path: /opt/icaro/sun-api/templates
    state: directory
    recurse: yes

- name: Download default logo
  get_url:
    url: "{{ icaro.sun_api.captive_portal_logo }}"
    force: true
    dest: /opt/icaro/static/logo.png

- name: Download default banner
  get_url:
    url: "{{ icaro.sun_api.captive_portal_banner }}"
    force: true
    dest: /opt/icaro/static/banner.png

- name: Download default background image
  get_url:
    url: "{{ icaro.sun_api.bg_image }}"
    force: true
    dest: /opt/icaro/static/bgImage.jpg

- name: Create Sun-api working directory
  file:
    path: /opt/icaro/sun-api/
    state: directory
    recurse: yes

- name: Copy Sun-api configuration file
  template:
    src: sun-api-conf.j2
    dest: /opt/icaro/sun-api/conf.json

- name: Download Ade-tasks templates
  get_url:
    url: "{{ icaro.url }}/raw/{{ icaro.version }}/ade/ade-tasks/templates/{{ item }}"
    force: true
    dest: /opt/icaro/sun-api/templates
    mode: 0644
  with_items:
    - feedback_user.tpl
    - review_user.tpl

- name: Download and install Sun-api executable
  get_url:
    url: "{{ icaro.url }}/releases/download/{{ icaro.version }}/sun-api"
    force: true
    dest: /opt/icaro/sun-api/sun-api
    mode: 0755

- name: Copy Sun-api sytemd unit
  copy:
    src: usr/lib/systemd/system/sun-api.service
    dest: /usr/lib/systemd/system/sun-api.service

- name: Enable sun-api service
  systemd:
    name: sun-api
    daemon_reload: yes
    enabled: yes
