---
- name: Create Ade-ui root directory
  file:
    path: /opt/icaro/ade-ui/
    state: directory
    recurse: yes

- name: Download Ade-ui package
  get_url:
    url: "{{ icaro.url }}/releases/download/{{ icaro.version }}/ade-ui.tar.gz"
    force: yes
    dest: /tmp/ade-ui.tar.gz

- name: Unpack Ade-ui package
  unarchive:
    src: /tmp/ade-ui.tar.gz
    dest: /opt/icaro/ade-ui/
    remote_src: yes
- block:
    - name: Download Ade-ui assets
      get_url:
        url: "{{ icaro.ade_ui.assets_url }}"
        force: yes
        dest: /tmp/ade-ui-assets.tar
    - name: Unpack Ade-ui assets
      unarchive:
        src: /tmp/ade-ui-assets.tar
        dest: /opt/icaro/ade-ui/static/
        remote_src: yes
  when: icaro.ade_ui is defined and icaro.ade_ui.assets_url is defined

- name: Remove temp files
  file:
    path:
      - /tmp/ade-ui.tar.gz
      - /tmp/ade-ui-assets.tar
    state: absent
